export default Image = {
    logo: require('./logo.png'),
    icecream: require('./ice.png'),
    bigicecream: require('./bigicecream.png'),
    girl: require('./girl.png'),
    pinkice: require('./pinkice.png'),
    chocolateice: require('./chocolate.png'),
    ClassicFavImage1: require('./ClassicFavImage1.png'),
    ClassicFavImage2: require('./ClassicFavImage2.png'),
    ClassicFavImage3: require('./ClassicFavImage3.png'),
    ClassicFavImage4: require('./ClassicFavImage4.png'),
    CategoryImage1: require('./CategoryImage1.jpg'),
    CategoryIamge2: require('./CategoryImage2.jpg'),
    CategoryImage3: require('./CategoryImage3.jpg'),
    CategoryImage4: require('./CategoryImage4.jpg'),
    // cat2: require('../images/cat-2.jpg'),
    // cat3: require('../images/cat-3.jpg'),
    // cat4: require('../images/cat-4.jpg'),
    // bg1 : require('../images/bg_1.jpg'),
    // bg2 : require('../images/bg_2.jpg'),
    
};
