export default Image = {
    logo: require('./logo.png'),
    icecream: require('./ice.png'),
    bigicecream: require('./bigicecream.png'),
    girl: require('./girl.png'),
    pinkice: require('./pinkice.png'),
    chocolateice: require('./chocolate.png'),
    ClassicFavImage1: require('./ClassicFavImage1.png'),
    ClassicFavImage2: require('./ClassicFavImage2.png'),
    ClassicFavImage3: require('./ClassicFavImage3.png'),
    ClassicFavImage4: require('./ClassicFavImage4.png'),
    CategoryImage1: require('./CategoryImage1.jpg'),
    CategoryIamge2: require('./CategoryImage2.jpg'),
    CategoryImage3: require('./CategoryImage3.jpg'),
    CategoryImage4: require('./CategoryImage4.jpg'),
    Home1Comp7People1: require('./Home1Comp7People1.png'),
    Home1Comp7Person2: require("./Home1Comp7Person2.png"),
    Home1Comp7Person3: require("./Home1Comp7Person3.png"),
    Home1Comp7Person4: require("./Home1Comp7Person4.png"),
    Home1Comp7Person5: require("./Home1Comp7Person5.png"),
    Home1Comp7Person6: require("./Home1Comp7Person6.png"),
    SideTraingle : require('./SideTriangles.png'),
    SideCircles: require('./SideCircles.png'),
    PlainCardImage1: require("./PlainCardsImage1.jpg"),
    PlainCardImage2: require("./PlainCardsImage2.jpg"),
    PlainCardImage3: require("./PlainCardsImage3.jpg"),
    PlainCardImage4: require("./PlainCardsImage4.jpg"),
    PlainCardImage5: require("./PlainCardsImage5.jpg"),
    iceBox: require("./IceBoxes.png"),
    halfcircles:require("./HalfSideCircles.png"),
    dots: require('./dots.png'),
    snakes:require('./snakes.png'),
    string: require('./string.png'),
    Home2Comp3Image: require("./Home2Comp3Image.jpg"),
    discount: require("./discount.png"),
    CarouselPic1: require("./CarouselPic1.jpg"),
    CarouselPic2: require("./CarouselPic2.jpg"),
    CarouselPic3: require("./CarouselPic3.jpg"),
    Home2Comp5Image1: require("./Home2Comp5Image1.png"),
    Home2Comp5Image2: require("./Home2Comp5Image2.png"),
    singleColorSnake: require("./singlecolorsnake.png"),
    violetBlocks: require("./violetblocks.png"),
    Home2Comp9FooterImage1: require("./Home2Comp9FooterImage1.jpg"),
    Home2Comp9FooterImage2: require("./Home2Comp9FooterImage2.jpg"),
    Home2Comp9FooterImage3: require("./Home2Comp9FooterImage3.jpg"),
    Home2Comp9FooterImage4: require("./Home2Comp9FooterImage4.jpg"),
    Home2Comp9FooterImage5: require("./Home2Comp9FooterImage5.jpg"),
    Home2Comp9FooterImage6: require("./Home2Comp9FooterImage6.jpg"),
    Home3Comp1Bg: require("./Home3Comp1Bg.jpg"),
    Home3Comp2Image: require("./Home3Comp2Image.png"),
    twoCircles: require("./twoCircles.png"),
    gelatoImage1: require("./gelatoImage1.png"),
    gelatoImage2: require("./gelatoImage2.png"),
    gelatoImage3: require("./gelatoImage3.png"),
    gelatoImage4: require("./gelatoImage4.png"),
    icecreamBowl: require("./iceCreamBowl.png"),
    wpsideTriangles: require("./wpsidetriangles.png"),
    crossCircle: require("./crossCircle.png"),
    two6: require("./two6.png"),
    AboutusComp2Image: require("./AboutusComp2Image.jpg"),
    AboutusComp3Image: require("./AboutusComp3Image.png"),
    TeamMember1: require("./TeamMember1.jpg"),
    TeamMember2: require("./TeamMember2.jpg"),
    TeamMember3: require("./TeamMember3.jpg"),
    TeamMember4: require("./TeamMember4.jpg"),
    TeamMember5: require("./TeamMember5.jpg"),
    TeamMember6: require("./TeamMember6.jpg"),
    smiley: require("./smiley.png"),
    pinkBg: require("./pinkBg.png"),
    offerBowl: require("./offerBowl.png"),
    CommitmentIcecream: require("./CommitmentIceCream.png"),
    ChocoChipCone: require("./ChocoChipCone.png"),
    strawberrySundae: require("./strawberrySundae.png"),
    paymentCards: require("./PaymentCards.png"),
    loginIce: require("./loginIce.png")


    

    
};
